import { NextResponse } from "next/server";

// Static data-model metadata for the ERD / Data Dictionary viewer.
const SCHEMA = [
  {
    table: "Organization",
    group: "Master",
    description: "ساختار سلسله‌مراتبی سازمان (شرکت → معاونت → مدیریت → واحد). خود‌ارجاعی با parentOrgId.",
    fields: [
      { name: "id", type: "String", pk: true, required: true, desc: "شناسه یکتا (CUID)" },
      { name: "code", type: "String", unique: true, required: true, desc: "کد یکتای سازمان (CO, DEP-MARKET, M-IT...)" },
      { name: "name", type: "String", required: true, desc: "نام رسمی" },
      { name: "displayName", type: "String", required: true, desc: "نام نمایشی" },
      { name: "orgType", type: "String", required: true, default: "MANAGEMENT", desc: "COMPANY | DEPUTY | MANAGEMENT | UNIT | DEPARTMENT | GROUP | OTHER" },
      { name: "level", type: "Int", default: "0", desc: "سطح در درخت (0=شرکت، 1=معاونت، 2=مدیریت)" },
      { name: "parentOrgId", type: "String?", fk: "Organization.id", desc: "ارجاع به والد" },
      { name: "responsibleId", type: "String?", fk: "User.id", desc: "کاربر مسئول" },
      { name: "isActive", type: "Boolean", default: "true" },
      { name: "createdAt / updatedAt", type: "DateTime", desc: "زمان‌سنجی" },
      { name: "createdBy / updatedBy", type: "String?", desc: "کاربر ایجاد/ویرایش" },
    ],
  },
  {
    table: "UnitDictionary",
    group: "Dictionary",
    description: "نگاشت نام‌های خام Excel (فاوا، آی‌تی، IT) به واحد کانونیکال. هسته استانداردسازی.",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "canonicalOrgId", type: "String", required: true, fk: "Organization.id", desc: "واحد کانونیکال مرجع" },
      { name: "originalName", type: "String", required: true, desc: "نام خام در منبع" },
      { name: "normalizedName", type: "String", required: true, desc: "نام نرمال‌شده برای تطبیق" },
      { name: "aliasType", type: "String", default: "ALIAS", desc: "ALIAS | SYNONYM | ABBREVIATION | LEGACY | TYPO | CANONICAL" },
      { name: "source", type: "String", default: "EXCEL", desc: "EXCEL | MANUAL | IMPORT" },
      { name: "confidence", type: "Float", default: "1.0", desc: "۰..۱" },
      { name: "isActive", type: "Boolean", default: "true" },
      { name: "createdAt", type: "DateTime" },
    ],
  },
  {
    table: "DictionaryTerm",
    group: "Dictionary",
    description: "فرهنگ‌نامه عمومی برای نگاشت هر مفهوم (سازمان، پروژه، وضعیت...).",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "entityType", type: "String", desc: "ORGANIZATION | PROJECT | TASK | STATUS ..." },
      { name: "canonicalId", type: "String", desc: "شناسه موجودیت کانونیکال" },
      { name: "originalTerm / normalizedTerm", type: "String", desc: "عبارت خام / نرمال‌شده" },
      { name: "termType", type: "String", default: "ALIAS", desc: "SYNONYM | ALIAS | ABBREVIATION | LEGACY | TYPO" },
      { name: "source / confidence", type: "String / Float" },
      { name: "notes", type: "String?" },
    ],
  },
  {
    table: "StatusDictionary",
    group: "Dictionary",
    description: "واژگان کنترل‌شدهٔ وضعیت‌ها (جلوگیری از متن آزاد).",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "statusCode", type: "String", unique: true, desc: "NOT_STARTED | IN_PROGRESS | COMPLETED | DELAYED | ON_HOLD | CANCELLED" },
      { name: "statusName", type: "String", desc: "نام فارسی" },
      { name: "entityType", type: "String", default: "TASK" },
      { name: "color", type: "String?", desc: "کد رنگ" },
      { name: "isActive", type: "Boolean" },
    ],
  },
  {
    table: "User",
    group: "Master",
    description: "کاربران سیستم برای مالکیت و ممیزی.",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "email", type: "String", unique: true },
      { name: "name", type: "String" },
      { name: "role", type: "String", default: "VIEWER", desc: "ADMIN | MANAGER | EDITOR | VIEWER" },
      { name: "isActive", type: "Boolean" },
    ],
  },
  {
    table: "Project",
    group: "Master",
    description: "هر شیت Excel = یک برنامه/پروژه مستقل. از parentProjectId برای ساختار والد/فرزند پشتیبانی می‌کند.",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "projectCode", type: "String", unique: true, desc: "کد یکتا (PRG-1405-M-IT-3-...)" },
      { name: "projectName / programTitle", type: "String", desc: "عنوان پروژه / برنامه" },
      { name: "projectType", type: "String", default: "PROGRAM", desc: "PROGRAM | PROJECT | SUBPROJECT" },
      { name: "ownerOrgId", type: "String?", fk: "Organization.id", desc: "مدیریت اصلی متولی" },
      { name: "parentProjectId", type: "String?", fk: "Project.id", desc: "پروژه والد" },
      { name: "goal", type: "String?", desc: "هدف برنامه" },
      { name: "year", type: "Int", default: "1405", desc: "سال شمسی" },
      { name: "programNumber", type: "Int?", desc: "شماره برنامه در مدیریت" },
      { name: "startDate / endDate", type: "DateTime?", desc: "تاریخ میلادی (محاسبه از جلالی)" },
      { name: "startJalali / endJalali", type: "String?", desc: "تاریخ خام شمسی" },
      { name: "plannedDuration", type: "Int?", desc: "مدت بر حسب روز" },
      { name: "status", type: "String", default: "NOT_STARTED" },
      { name: "priority", type: "String", default: "NORMAL" },
      { name: "overallWeight", type: "Float", default: "100", desc: "وزن برنامه" },
      { name: "progressPercent", type: "Float", default: "0", desc: "پیشرفت وزنی Roll-up" },
      { name: "isActive", type: "Boolean" },
      { name: "createdAt / updatedAt", type: "DateTime" },
    ],
  },
  {
    table: "ProjectUnit",
    group: "Transaction",
    description: "رابطه چند‌به‌چند پروژه ↔ سازمان با نقش (مالک/همکار/نظارت...).",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "projectId", type: "String", required: true, fk: "Project.id" },
      { name: "orgId", type: "String", required: true, fk: "Organization.id" },
      { name: "roleType", type: "String", default: "RESPONSIBLE", desc: "OWNER | RESPONSIBLE | COLLABORATOR | SUPERVISOR | CONSULTANT | APPROVER" },
      { name: "responsibilityWeight", type: "Float", default: "0" },
      { name: "isPrimary", type: "Boolean", default: "false" },
      { name: "participationPercent", type: "Float", default: "0" },
    ],
  },
  {
    table: "Task",
    group: "Master",
    description: "فعالیت/وظیفه. خود‌ارجاعی برای زیر‌فعالیت. شامل وزن، تاریخ، پیشرفت، وضعیت.",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "projectId", type: "String", required: true, fk: "Project.id" },
      { name: "parentTaskId", type: "String?", fk: "Task.id", desc: "وظیفه والد" },
      { name: "taskCode", type: "String?", desc: "T-001" },
      { name: "taskName", type: "String", required: true, desc: "شرح عملیات" },
      { name: "taskType", type: "String", default: "ACTIVITY", desc: "ACTIVITY | DELIVERABLE | MILESTONE | PHASE" },
      { name: "sequenceNo", type: "Int", default: "0", desc: "ردیف" },
      { name: "weight", type: "Float", default: "0", desc: "وزن هر عملیات" },
      { name: "progressPercent", type: "Float", default: "0" },
      { name: "status", type: "String", default: "NOT_STARTED" },
      { name: "startJalali / endJalali", type: "String?" },
      { name: "startDate / endDate", type: "DateTime?" },
      { name: "duration", type: "Int?", desc: "روز" },
      { name: "isMilestone", type: "Boolean", default: "false" },
      { name: "target", type: "String?", desc: "هدف کمی" },
      { name: "prereq", type: "String?", desc: "پیش‌نیازی گام‌ها" },
      { name: "notes", type: "String?", desc: "ملاحظات" },
      { name: "activeMonths", type: "String?", desc: "آرایه JSON شماره ماه‌های فعال [2,3,4]" },
    ],
  },
  {
    table: "TaskUnit",
    group: "Transaction",
    description: "رابطه چند‌به‌چند وظیفه ↔ سازمان (واحدهای مجری).",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "taskId", type: "String", fk: "Task.id" },
      { name: "orgId", type: "String", fk: "Organization.id" },
      { name: "roleType", type: "String", default: "EXECUTOR", desc: "EXECUTOR | OWNER | COLLABORATOR" },
      { name: "isPrimary", type: "Boolean", default: "false" },
    ],
  },
  {
    table: "TaskDependency",
    group: "Transaction",
    description: "وابستگی بین وظایف به سبک MS Project (FS/SS/FF/SF + lag).",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "predecessorTaskId", type: "String", fk: "Task.id" },
      { name: "successorTaskId", type: "String", fk: "Task.id" },
      { name: "dependencyType", type: "String", default: "FS", desc: "FS | SS | FF | SF" },
      { name: "lag", type: "Int", default: "0", desc: "روز" },
    ],
  },
  {
    table: "TaskProgressHistory",
    group: "Transaction",
    description: "سری زمانی پیشرفت وظیفه برای نمودار S-Curve و Planned vs Actual.",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "taskId", type: "String", fk: "Task.id" },
      { name: "orgId", type: "String?", fk: "Organization.id" },
      { name: "reportDate", type: "DateTime", desc: "تاریخ گزارش" },
      { name: "reportJalali", type: "String?", desc: "تاریخ شمسی" },
      { name: "progressPercent", type: "Float", desc: "پیشرفت واقعی" },
      { name: "plannedProgressPercent", type: "Float", desc: "پیشرفت برنامه‌ریزی‌شده" },
      { name: "actualProgressPercent", type: "Float" },
      { name: "comment", type: "String?" },
      { name: "recordedById", type: "String?", fk: "User.id" },
    ],
  },
  {
    table: "ProjectProgressHistory",
    group: "Transaction",
    description: "اسنپ‌شات ماهانه پیشرفت وزنی پروژه.",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "projectId", type: "String", fk: "Project.id" },
      { name: "reportDate / reportJalali", type: "DateTime / String" },
      { name: "progressPercent / plannedProgressPercent", type: "Float" },
    ],
  },
  {
    table: "AuditLog",
    group: "Audit",
    description: "ثبت تغییرات موجودیت‌های حساس.",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "entityType / entityId", type: "String", desc: "نوع و شناسه موجودیت" },
      { name: "action", type: "String", desc: "CREATE | UPDATE | DELETE" },
      { name: "oldValue / newValue", type: "String?", desc: "JSON" },
      { name: "userId", type: "String?", fk: "User.id" },
      { name: "createdAt", type: "DateTime" },
    ],
  },
  {
    table: "ImportBatch",
    group: "Raw",
    description: "رهگیری یک اجرای ETL.",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "fileName / batchLabel", type: "String" },
      { name: "startedAt / finishedAt", type: "DateTime" },
      { name: "sheetsProcessed / rowsProcessed", type: "Int" },
      { name: "status", type: "String", desc: "RUNNING | DONE | FAILED" },
    ],
  },
  {
    table: "RawSheetImport",
    group: "Raw",
    description: "یک رکورد به ازای هر شیت Excel وارد‌شده. لایه Raw.",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "batchId", type: "String", fk: "ImportBatch.id" },
      { name: "sheetName", type: "String" },
      { name: "projectTitle / managerRaw / programTitle", type: "String?", desc: "داده خام سربرگ" },
      { name: "programNum / weight", type: "Int? / Float?" },
      { name: "startDateRaw / endDateRaw / goalRaw", type: "String?" },
      { name: "mappedProjectId", type: "String?", desc: "پروژه نگاشت‌شده" },
      { name: "rowCount", type: "Int" },
      { name: "status", type: "String" },
    ],
  },
  {
    table: "RawProgramRow",
    group: "Raw",
    description: "یک رکورد به ازای هر ردیف خام تسک در شیت. لایه Raw با قابلیت Trace.",
    fields: [
      { name: "id", type: "String", pk: true },
      { name: "sheetImportId", type: "String", fk: "RawSheetImport.id" },
      { name: "rowNumber", type: "Int" },
      { name: "rawJson", type: "String", desc: "تمام سلول‌های خام به صورت JSON" },
      { name: "taskDesc / weight / executorsRaw / target / prereq / notes", type: "mixed" },
      { name: "activeMonthsRaw", type: "String?", desc: "JSON ماه‌های فعال" },
      { name: "mappedTaskId", type: "String?", fk: "Task.id" },
      { name: "mappingStatus", type: "String", default: "PENDING", desc: "PENDING | MAPPED | UNMAPPED | CONFLICT" },
    ],
  },
];

export async function GET() {
  return NextResponse.json({
    tables: SCHEMA,
    groups: ["Master", "Dictionary", "Transaction", "Audit", "Raw"],
    relationships: [
      { from: "Organization", to: "Organization", type: "self-ref (parentOrgId)", label: "درخت سلسله‌مراتبی" },
      { from: "UnitDictionary", to: "Organization", type: "N:1 (canonicalOrgId)", label: "نگاشت نام به واحد کانونیکال" },
      { from: "Project", to: "Organization", type: "N:1 (ownerOrgId)", label: "مالک پروژه" },
      { from: "Project", to: "Project", type: "self-ref (parentProjectId)", label: "پروژه والد/فرزند" },
      { from: "ProjectUnit", to: "Project / Organization", type: "M:N junction", label: "پروژه ↔ سازمان" },
      { from: "Task", to: "Project", type: "N:1 (projectId)", label: "وظایف پروژه" },
      { from: "Task", to: "Task", type: "self-ref (parentTaskId)", label: "زیر‌فعالیت" },
      { from: "TaskUnit", to: "Task / Organization", type: "M:N junction", label: "وظیفه ↔ واحد مجری" },
      { from: "TaskDependency", to: "Task", type: "2× FK", label: "وابستگی پیش‌نیاز/پس‌نیاز" },
      { from: "TaskProgressHistory", to: "Task", type: "N:1", label: "تاریخچه پیشرفت" },
      { from: "RawSheetImport", to: "Project", type: "1:1 (mappedProjectId)", label: "نگاشت شیت خام به پروژه" },
      { from: "RawProgramRow", to: "Task", type: "1:1 (mappedTaskId)", label: "نگاشت ردیف خام به وظیفه" },
    ],
  });
}
